#############################################################################
# Makefile for building: Skil3.app/Contents/MacOS/Skil3
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Skil3.pro
# Template: app
# Command: /Users/Darri/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile Skil3.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.7/clang_64/lib/QtSql.framework/Headers -I../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/Darri/Qt/5.7/clang_64/lib
QMAKE         = /Users/Darri/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Skil31.0.0
DISTDIR = /Users/Darri/skil-3-master/Skil3/.tmp/Skil31.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/Darri/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Darri/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		entity/entity.cpp \
		entity/computer/computer.cpp \
		entity/connection/connection.cpp \
		entity/entitymanager.cpp \
		entity/person/person.cpp \
		snake/snake.cpp \
		snake/snakegrid.cpp \
		snake/snakescore.cpp \
		snake/snakethread.cpp \
		snake/snakewidget.cpp \
		console.cpp \
		storage/storage.cpp \
		userinterface.cpp \
		pong/pongwidget.cpp \
		pong/pong.cpp \
		pong/pongracket.cpp \
		pong/pongthread.cpp \
		pong/pongball.cpp \
		entity/person/addpersondialog.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_snakethread.cpp \
		moc_pongthread.cpp \
		moc_addpersondialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		entity.o \
		computer.o \
		connection.o \
		entitymanager.o \
		person.o \
		snake.o \
		snakegrid.o \
		snakescore.o \
		snakethread.o \
		snakewidget.o \
		console.o \
		storage.o \
		userinterface.o \
		pongwidget.o \
		pong.o \
		pongracket.o \
		pongthread.o \
		pongball.o \
		addpersondialog.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_snakethread.o \
		moc_pongthread.o \
		moc_addpersondialog.o
DIST          = ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Skil3.pro mainwindow.h \
		entity/entity.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		entity/entitymanager.h \
		entity/person/person.h \
		snake/snake.h \
		snake/snakegrid.h \
		snake/snakescore.h \
		snake/snakethread.h \
		snake/snakewidget.h \
		console.h \
		storage/storage.h \
		config.h \
		userinterface.h \
		pong/pongwidget.h \
		pong/pong.h \
		pong/pongracket.h \
		pong/pongthread.h \
		pong/pongball.h \
		entity/person/addpersondialog.h main.cpp \
		mainwindow.cpp \
		entity/entity.cpp \
		entity/computer/computer.cpp \
		entity/connection/connection.cpp \
		entity/entitymanager.cpp \
		entity/person/person.cpp \
		snake/snake.cpp \
		snake/snakegrid.cpp \
		snake/snakescore.cpp \
		snake/snakethread.cpp \
		snake/snakewidget.cpp \
		console.cpp \
		storage/storage.cpp \
		userinterface.cpp \
		pong/pongwidget.cpp \
		pong/pong.cpp \
		pong/pongracket.cpp \
		pong/pongthread.cpp \
		pong/pongball.cpp \
		entity/person/addpersondialog.cpp
QMAKE_TARGET  = Skil3
DESTDIR       = 
TARGET        = Skil3.app/Contents/MacOS/Skil3


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_addpersondialog.h $(OBJECTS)  
	@test -d Skil3.app/Contents/MacOS/ || mkdir -p Skil3.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Skil3.pro ../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Skil3.pro \
		resources.qrc \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.7/clang_64/lib/QtSql.framework/QtSql.prl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Skil3.pro
../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Skil3.pro:
resources.qrc:
../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.7/clang_64/lib/QtSql.framework/QtSql.prl:
../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Skil3.pro

qmake_all: FORCE

Skil3.app/Contents/PkgInfo: 
	@test -d Skil3.app/Contents || mkdir -p Skil3.app/Contents
	@$(DEL_FILE) Skil3.app/Contents/PkgInfo
	@echo "APPL????" > Skil3.app/Contents/PkgInfo
Skil3.app/Contents/Resources/empty.lproj: 
	@test -d Skil3.app/Contents/Resources || mkdir -p Skil3.app/Contents/Resources
	@touch Skil3.app/Contents/Resources/empty.lproj
	
Skil3.app/Contents/Info.plist: 
	@test -d Skil3.app/Contents || mkdir -p Skil3.app/Contents
	@$(DEL_FILE) Skil3.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Skil3,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Skil3,g" -e "s,@LIBRARY@,Skil3,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Skil3.app/Contents/Info.plist

all: Makefile \
		Skil3.app/Contents/PkgInfo \
		Skil3.app/Contents/Resources/empty.lproj \
		Skil3.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h entity/entity.h entity/computer/computer.h entity/connection/connection.h entity/entitymanager.h entity/person/person.h snake/snake.h snake/snakegrid.h snake/snakescore.h snake/snakethread.h snake/snakewidget.h console.h storage/storage.h config.h userinterface.h pong/pongwidget.h pong/pong.h pong/pongracket.h pong/pongthread.h pong/pongball.h entity/person/addpersondialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp entity/entity.cpp entity/computer/computer.cpp entity/connection/connection.cpp entity/entitymanager.cpp entity/person/person.cpp snake/snake.cpp snake/snakegrid.cpp snake/snakescore.cpp snake/snakethread.cpp snake/snakewidget.cpp console.cpp storage/storage.cpp userinterface.cpp pong/pongwidget.cpp pong/pong.cpp pong/pongracket.cpp pong/pongthread.cpp pong/pongball.cpp entity/person/addpersondialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui entity/person/addpersondialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Skil3.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../Qt/5.7/clang_64/bin/rcc \
		icons/add.png \
		icons/people_icon.jpg
	/Users/Darri/Qt/5.7/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_snakethread.cpp moc_pongthread.cpp moc_addpersondialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_snakethread.cpp moc_pongthread.cpp moc_addpersondialog.cpp
moc_mainwindow.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItem \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QItemSelectionModel \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		userinterface.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		config.h \
		entity/entity.h \
		entity/person/person.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		entity/entitymanager.h \
		console.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		snake/snakescore.h \
		snake/snake.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		snake/snakegrid.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pong.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		pong/pongball.h \
		pong/pongracket.h \
		mainwindow.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/Darri/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Darri/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Darri/skil-3-master/Skil3 -I/Users/Darri/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/Darri/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_snakethread.cpp: ../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		snake/snakegrid.h \
		console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/Darri/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Darri/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Darri/skil-3-master/Skil3 -I/Users/Darri/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/Darri/Qt/5.7/clang_64/lib snake/snakethread.h -o moc_snakethread.cpp

moc_pongthread.cpp: ../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pongball.h \
		pong/pongracket.h \
		config.h \
		pong/pongwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		pong/pongthread.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/Darri/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Darri/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Darri/skil-3-master/Skil3 -I/Users/Darri/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/Darri/Qt/5.7/clang_64/lib pong/pongthread.h -o moc_pongthread.cpp

moc_addpersondialog.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		entity/entitymanager.h \
		config.h \
		console.h \
		entity/person/person.h \
		entity/entity.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		snake/snakescore.h \
		entity/person/addpersondialog.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/Darri/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Darri/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Darri/skil-3-master/Skil3 -I/Users/Darri/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtSql.framework/Headers -I/Users/Darri/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/Darri/Qt/5.7/clang_64/lib entity/person/addpersondialog.h -o moc_addpersondialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_addpersondialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_addpersondialog.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/5.7/clang_64/bin/uic
	/Users/Darri/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_addpersondialog.h: entity/person/addpersondialog.ui \
		../../Qt/5.7/clang_64/bin/uic
	/Users/Darri/Qt/5.7/clang_64/bin/uic entity/person/addpersondialog.ui -o ui_addpersondialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItem \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QItemSelectionModel \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		userinterface.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		config.h \
		entity/entity.h \
		entity/person/person.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		entity/entitymanager.h \
		console.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		snake/snakescore.h \
		snake/snake.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		snake/snakegrid.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pong.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		pong/pongball.h \
		pong/pongracket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItem \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QItemSelectionModel \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		userinterface.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		config.h \
		entity/entity.h \
		entity/person/person.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		entity/entitymanager.h \
		console.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		snake/snakescore.h \
		snake/snake.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		snake/snakegrid.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pong.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		pong/pongball.h \
		pong/pongracket.h \
		ui_mainwindow.h \
		entity/person/addpersondialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

entity.o: entity/entity.cpp entity/entity.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entity.o entity/entity.cpp

computer.o: entity/computer/computer.cpp entity/computer/computer.h \
		entity/entity.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computer.o entity/computer/computer.cpp

connection.o: entity/connection/connection.cpp entity/connection/connection.h \
		entity/entity.h \
		config.h \
		entity/person/person.h \
		entity/computer/computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o entity/connection/connection.cpp

entitymanager.o: entity/entitymanager.cpp entity/entitymanager.h \
		config.h \
		console.h \
		entity/person/person.h \
		entity/entity.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		snake/snakescore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entitymanager.o entity/entitymanager.cpp

person.o: entity/person/person.cpp entity/person/person.h \
		entity/entity.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o entity/person/person.cpp

snake.o: snake/snake.cpp snake/snake.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		snake/snakegrid.h \
		console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snake.o snake/snake.cpp

snakegrid.o: snake/snakegrid.cpp snake/SnakeGrid.h \
		console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snakegrid.o snake/snakegrid.cpp

snakescore.o: snake/snakescore.cpp snake/snakescore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snakescore.o snake/snakescore.cpp

snakethread.o: snake/snakethread.cpp snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		snake/snakegrid.h \
		console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snakethread.o snake/snakethread.cpp

snakewidget.o: snake/snakewidget.cpp snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		snake/snakegrid.h \
		console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snakewidget.o snake/snakewidget.cpp

console.o: console.cpp console.h \
		config.h \
		entity/person/person.h \
		entity/entity.h \
		entity/entitymanager.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		snake/snakescore.h \
		snake/snake.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		snake/snakegrid.h \
		snake/snakewidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QRect \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		snake/snakethread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o console.cpp

storage.o: storage/storage.cpp storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		entity/person/person.h \
		entity/entity.h \
		config.h \
		entity/computer/computer.h \
		console.h \
		entity/connection/connection.h \
		snake/snakescore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o storage.o storage/storage.cpp

userinterface.o: userinterface.cpp userinterface.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		config.h \
		entity/entity.h \
		entity/person/person.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		entity/entitymanager.h \
		console.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		snake/snakescore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinterface.o userinterface.cpp

pongwidget.o: pong/pongwidget.cpp pong/pongwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		config.h \
		pong/pongball.h \
		pong/pongracket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pongwidget.o pong/pongwidget.cpp

pong.o: pong/pong.cpp pong/pong.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		pong/pongball.h \
		pong/pongracket.h \
		config.h \
		pong/pongthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pongwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pong.o pong/pong.cpp

pongracket.o: pong/pongracket.cpp pong/pongracket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pongracket.o pong/pongracket.cpp

pongthread.o: pong/pongthread.cpp pong/pongthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		pong/pongball.h \
		pong/pongracket.h \
		config.h \
		pong/pongwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPointF \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFontMetrics \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pongthread.o pong/pongthread.cpp

pongball.o: pong/pongball.cpp pong/pongball.h \
		pong/pongracket.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pongball.o pong/pongball.cpp

addpersondialog.o: entity/person/addpersondialog.cpp entity/person/addpersondialog.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		entity/entitymanager.h \
		config.h \
		console.h \
		entity/person/person.h \
		entity/entity.h \
		storage/storage.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsql.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Qt/5.7/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		entity/computer/computer.h \
		entity/connection/connection.h \
		snake/snakescore.h \
		ui_addpersondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addpersondialog.o entity/person/addpersondialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_snakethread.o: moc_snakethread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_snakethread.o moc_snakethread.cpp

moc_pongthread.o: moc_pongthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pongthread.o moc_pongthread.cpp

moc_addpersondialog.o: moc_addpersondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addpersondialog.o moc_addpersondialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

